#!/usr/bin/env python3
r"""Emit the paper's numbers as LaTeX macros and tables.

The paper must never contain a typed figure. This reads
model_trace/paper_metrics.json (itself derived from the lane outputs) and
writes paper/generated/results.tex, which main.tex \input{}s.

Run order:
    scripts/build_clinvar_evidence.py
    scripts/build_fasta_lane.py
    scripts/build_paper_metrics.py
    scripts/build_paper_tex.py        <- this

If a number in the compiled PDF disagrees with the pipeline, the pipeline is
right and the PDF is stale. That is the same rule the project applies to its
evidence, applied to its own write-up.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
METRICS = ROOT / "model_trace" / "paper_metrics.json"
OUT = ROOT / "paper" / "generated" / "results.tex"

BS = chr(92)  # backslash, built without an escape sequence


def cmd(name: str, value) -> str:
    return BS + "newcommand{" + BS + name + "}{" + str(value) + "}"


def pct(x) -> str:
    return f"{x * 100:.1f}" + BS + "%" if x is not None else "n/a"


def main() -> int:
    m = json.loads(METRICS.read_text(encoding="utf-8"))
    g1 = m["guards"]["G1_residue_verification"]
    g2 = m["guards"]["G2_copy_number_exclusion"]
    rec = m["corpus"]["reconciliation"]
    ret = m["retention"]
    zeroed = g2["genes_reduced_to_zero"]

    macros = {
        "GOneProcessed": g1["records_processed"],
        "GOneNotation": g1["with_protein_notation"],
        "GOneEligible": g1["substitution_eligible"],
        "GOneLoud": g1["excluded_loud_failures"],
        "GOneNaive": g1["naive_emits"],
        "GOneWrong": g1["silently_wrong"],
        "GOneRate": pct(g1["rate"]),
        "GOneEmits": g1["enforced_emits"],
        "GOneMissense": g1["missense"],
        "GOneTruncating": g1["truncating"],
        "GTwoNaive": g2["naive_emits"],
        "GTwoWrong": g2["silently_wrong"],
        "GTwoRate": pct(g2["rate"]),
        "GTwoEmits": g2["enforced_emits"],
        "GTwoZeroed": len(zeroed),
        "GTwoZeroedNames": ", ".join(zeroed),
        "NumGenes": len(g2["per_gene"]),
        "CorpusFetched": rec.get("ids_fetched", 0),
        "CorpusKept": rec.get("kept", 0),
        "CorpusExcluded": rec.get("excluded_large_cnv", 0),
        "CorpusUnavailable": rec.get("no_summary_returned", 0),
        "SeqDeclined": ret["sequence_lane"]["declined"],
        "CorpusDate": (m["corpus"].get("captured_at") or "")[:10],
        "CorpusDigest": m["corpus"]["clinvar_subset_sha256"][:12],
        "VariantsDigest": m["corpus"]["variants_fasta_sha256"][:12],
    }

    L = ["% GENERATED by scripts/build_paper_tex.py -- do not edit by hand.",
         "% Every figure the paper cites is defined here, derived from the",
         "% pipeline outputs. Regenerate after any lane rebuild.", ""]
    L += [cmd(k, v) for k, v in macros.items()]

    rowend = BS + BS
    L += ["", "% --- ablation ---",
          BS + "newcommand{" + BS + "AblationTable}{%",
          BS + "begin{tabular}{lrrrr}", BS + "toprule",
          f"Guard & Naive emits & Silently wrong & Rate & Enforced emits {rowend}",
          BS + "midrule",
          f"G1 residue verification & {g1['naive_emits']} & {g1['silently_wrong']} & "
          f"{pct(g1['rate'])} & {g1['enforced_emits']} {rowend}",
          f"G2 copy-number exclusion & {g2['naive_emits']} & {g2['silently_wrong']} & "
          f"{pct(g2['rate'])} & {g2['enforced_emits']} {rowend}",
          BS + "bottomrule", BS + "end{tabular}}", ""]

    L += ["% --- per-gene effect of G2 ---",
          BS + "newcommand{" + BS + "PerGeneTable}{%",
          BS + "begin{tabular}{lrrr}", BS + "toprule",
          f"Gene & Unfiltered & After G2 & Excluded {rowend}", BS + "midrule"]
    for r in g2["per_gene"]:
        star = "$^{*}$" if r["enforced"] == 0 and r["excluded"] > 0 else ""
        L.append(f"{r['gene']}{star} & {r['naive']} & {r['enforced']} & {r['excluded']} {rowend}")
    L += [BS + "bottomrule", BS + "end{tabular}}", ""]

    L += ["% --- why the sequence lane declines ---",
          BS + "newcommand{" + BS + "DeclineTable}{%",
          BS + "begin{tabular}{lr}", BS + "toprule",
          f"Reason declined & Records {rowend}", BS + "midrule"]
    for k, v in sorted(ret["sequence_lane"]["declined_reasons"].items(), key=lambda kv: -kv[1]):
        L.append(f"{k.replace('_', ' ')} & {v} {rowend}")
    L += [BS + "bottomrule", BS + "end{tabular}}", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(macros)} macros + 3 tables")
    print(f"  G1 {g1['silently_wrong']}/{g1['naive_emits']} = {pct(g1['rate'])}"
          f"   G2 {g2['silently_wrong']}/{g2['naive_emits']} = {pct(g2['rate'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
